# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  Build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cat ./packages/apollo-link/package.json ./packages/apollo-link-batch/package.json ./packages/apollo-link-batch-http/package.json ./packages/apollo-link-context/package.json ./packages/apollo-link-dedup/package.json ./packages/apollo-link-error/package.json ./packages/apollo-link-http/package.json ./packages/apollo-link-http-common/package.json ./packages/apollo-link-polling/package.json ./packages/apollo-link-retry/package.json ./packages/apollo-link-schema/package.json ./packages/apollo-link-ws/package.json ./packages/zen-observable-ts/package.json > package-checksum
      - restore_cache:
          keys:
            - npm-v2-{{ checksum "package-lock.json" }}-{{ checksum "package-checksum" }}
            - npm-v2-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - run: git checkout package.json
      - save_cache:
          key: npm-v2-{{ checksum "package-lock.json" }}-{{ checksum "package-checksum" }}
          paths:
            - ./node_modules
            - ./packages/apollo-link/node_modules
            - ./packages/apollo-link-batch/node_modules
            - ./packages/apollo-link-batch-http/node_modules
            - ./packages/apollo-link-context/node_modules
            - ./packages/apollo-link-dedup/node_modules
            - ./packages/apollo-link-error/node_modules
            - ./packages/apollo-link-http/node_modules
            - ./packages/apollo-link-http-common/node_modules
            - ./packages/apollo-link-polling/node_modules
            - ./packages/apollo-link-retry/node_modules
            - ./packages/apollo-link-schema/node_modules
            - ./packages/apollo-link-ws/node_modules
            - ./packages/zen-observable-ts/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  Danger:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - run: npm run danger

  Prettier Check:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - run: npm run lint-check

  Docs:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - npm-v2-{{ checksum "./docs/package-lock.json" }}
      - run:
          name: install-docs-npm
          command: cd docs && npm i
      - run: git checkout ./docs/package.json
      - save_cache:
          key: npm-v2-{{ checksum "./docs/package-lock.json" }}
          paths:
            - ./docs/node_modules
      - run: cd docs && npm run build

  Filesize:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: .
      - run: npm run filesize

  Monorepo:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v2-{{ .branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .branch }}-
            - npm-v2-
      - run: npm--version
      - run: npm ci
      - save_cache:
          key: npm-v2-{{ .branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

workflows:
  version: 2
  Build and Test:
    jobs:
      - Build
      - Danger:
          requires:
            - Build
      - Docs:
          requires:
            - Build
      - Prettier Check:
          requires:
            - Build
      - Filesize:
          requires:
            - Build
      - Monorepo:
          requires:
            - Build
