version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:10

attach: &attach
  attach_workspace:
    at: ~/project

jobs:
  Build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v2-{{ .Branch }}-
            - npm-v2-
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - .

  Danger:
    <<: *defaults
    steps:
      - <<: *attach
      - run: npm run danger

  Prettier Check:
    <<: *defaults
    steps:
      - <<: *attach
      - run: npm run lint-check

  Filesize:
    <<: *defaults
    steps:
      - <<: *attach
      - run: npm run build
      - run: npm run filesize

  Monorepo:
    <<: *defaults
    steps:
      - <<: *attach
      - run:
          name: Jest suite with coverage
          command: npm run test-ci && npm run coverage:upload
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit


workflows:
  version: 2
  Build and Test:
    jobs:
      - Build
      - Danger:
          requires:
            - Build
      - Prettier Check:
          requires:
            - Build
      - Filesize:
          requires:
            - Build
      - Monorepo:
          requires:
            - Build
