title: Apollo Link
propertytitle: Using Apollo Link
subtitle: Apollo Link Guide
description: A guide to using Apollo Link to customize Apollo Client.
versions:
  - '1'
sidebar_categories:
  null:
    - index
  Concepts:
    - overview
    - stateless
    - stateful
    - composition
  Links:
    - links/http
    - links/state
    - links/rest
    - links/error
    - links/context
    - links/retry
    - links/ws
    - links/batch-http
    - links/dedup
    - links/schema
    - links/community
github_repo: apollographql/apollo-link
content_root: docs/source

typescript_api_box:
  data_file: docs.json

url: https://www.apollographql.com/docs/link
root: /docs/link/

public_dir: public/docs/link

marked:
  gfm: true
  breaks: false
